#!/usr/bin/env bash
set -euo pipefail
INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; ENV_FILE="$INSTALL_DIR/config/config.env"
[[ ! -f "$ENV_FILE" ]] && echo "Missing config file: $ENV_FILE" && exit 1
source "$ENV_FILE"; source "$INSTALL_DIR/logger.sh"; source "$INSTALL_DIR/telegram.sh"; source "$INSTALL_DIR/utils.sh"; source "$INSTALL_DIR/cloudflare-api.sh"
SERVER_NAME="$(hostname -s 2>/dev/null || hostname)"; [[ "${1:-}" == "--startup" ]] && telegram_startup "$SERVER_NAME"
update_dns_record(){ local zone_name="$1" record_name="$2" record_type="$3" ttl="$4" proxied="$5" ip="$6"; [[ -z "$ip" ]] && { log_msg WARN "Skipping ${record_name} ${record_type}; no public IP detected."; return 0; }; local state_key="${zone_name}_${record_name}_${record_type}" cached_ip; cached_ip="$(json_get_state "$state_key" || true)"; if [[ "$cached_ip" == "$ip" ]]; then log_msg INFO "Cached IP unchanged for ${record_name} ${record_type}: ${ip}"; telegram_no_change "$record_name" "$record_type" "$ip" "$SERVER_NAME"; return 0; fi; zone_id="$(get_zone_id "$zone_name")"; [[ -z "$zone_id" ]] && { log_msg ERROR "Zone not found or token lacks access: $zone_name"; telegram_error "Zone not found or token lacks access: $zone_name" "$SERVER_NAME"; return 1; }; record_id="$(get_record_id "$zone_id" "$record_name" "$record_type")"; if [[ -z "$record_id" ]]; then log_msg WARN "Creating missing record ${record_name} ${record_type}"; response="$(create_record "$zone_id" "$record_name" "$record_type" "$ip" "$ttl" "$proxied")"; if [[ "$(echo "$response"|jq -r '.success')" == true ]]; then json_set_state "$state_key" "$ip"; telegram_updated "$record_name" "$record_type" "not-created" "$ip" "$SERVER_NAME"; verify_dns_propagation "$record_name" "$record_type" "$ip" "$proxied"; return 0; fi; telegram_error "Failed to create $record_name $record_type" "$SERVER_NAME"; return 1; fi; cloudflare_ip="$(get_record_content "$zone_id" "$record_id")"; if [[ "$cloudflare_ip" == "$ip" ]]; then json_set_state "$state_key" "$ip"; log_msg INFO "Cloudflare already current for ${record_name}: ${ip}"; telegram_no_change "$record_name" "$record_type" "$ip" "$SERVER_NAME"; return 0; fi; response="$(update_record "$zone_id" "$record_id" "$record_name" "$record_type" "$ip" "$ttl" "$proxied")"; if [[ "$(echo "$response"|jq -r '.success')" == true ]]; then json_set_state "$state_key" "$ip"; log_msg INFO "Updated ${record_name}: ${cloudflare_ip} -> ${ip}"; telegram_updated "$record_name" "$record_type" "$cloudflare_ip" "$ip" "$SERVER_NAME"; verify_dns_propagation "$record_name" "$record_type" "$ip" "$proxied"; else telegram_error "Failed to update $record_name $record_type" "$SERVER_NAME"; return 1; fi; }
main(){ log_msg INFO "Starting DDNS check"; if [[ "$(validate_token)" != true ]]; then telegram_error "Cloudflare API token validation failed" "$SERVER_NAME"; exit 1; fi; ipv4="$(get_public_ipv4)"; if ! is_valid_ipv4 "$ipv4"; then log_msg WARN "Unable to detect valid IPv4 after fallback providers."; ipv4=""; else log_msg INFO "Detected public IPv4: $ipv4"; fi; ipv6="$(get_public_ipv6)"; is_valid_ipv6 "$ipv6" || ipv6=""; while IFS='|' read -r zone_name record_name record_type ttl proxied; do [[ -z "${zone_name:-}" || "$zone_name" =~ ^# ]] && continue; zone_name="$(trim_spaces "$zone_name")"; record_name="$(trim_spaces "$record_name")"; record_type="$(trim_spaces "${record_type:-A}")"; ttl="$(trim_spaces "${ttl:-120}")"; proxied="$(trim_spaces "${proxied:-false}")"; case "$record_type" in A) update_dns_record "$zone_name" "$record_name" A "$ttl" "$proxied" "$ipv4";; AAAA) update_dns_record "$zone_name" "$record_name" AAAA "$ttl" "$proxied" "$ipv6";; BOTH) update_dns_record "$zone_name" "$record_name" A "$ttl" "$proxied" "$ipv4"; update_dns_record "$zone_name" "$record_name" AAAA "$ttl" "$proxied" "$ipv6";; *) log_msg WARN "Invalid record type for ${record_name}: ${record_type}";; esac; done < "$RECORDS_FILE"; log_msg INFO "DDNS check completed"; }
main "$@"
